services:
    # database
    db:
        platform: linux/x86_64
        image: mysql:8.4
        volumes:
            - db_data:/var/lib/mysql
        # restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_management
            MYSQL_PASSWORD: root
        networks:
            - mysql-phpmyadmin

    # phpmyadmin
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin:5.0
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        networks:
            - mysql-phpmyadmin

networks:
    mysql-phpmyadmin:
        driver: bridge

volumes:
    db_data:
        driver: local
